version: "3.8"
services:
  web:
    image: odoo:18
    depends_on: 
      - db
    ports:
      - "8069:8069"
    volumes:  
    #aqui deben ir los directorios de mi pc windows
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - odoo-db-data-files:/var/lib/postgresql/data/db-files/

volumes:
  odoo-web-data:
  odoo-db-data-files: