version: "3.8"

services:

  odoo:
    image: odoo:18
    container_name: odoo-container
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo  # Contiene odoo.conf
      - ./extra-addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - LANG=C.UTF-8
    networks:
      - general-net
    command: odoo -c /etc/odoo/odoo.conf

  db:
    image: postgres:16
    container_name: db-container
    restart: unless-stopped
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - general-net

volumes:
  odoo-data:
  db-data:

networks:
  general-net:
    driver: bridge
